### ISSUE TITLE
The `speedy` container does not stay running

### ISSUE THREAD

**Issue by tstackhouse** [stefanwalther/speedy#6]
When using the `speedy` container, it doesn't stay running, and therefore the scheduled speedtests never run.  See the output from my logs:

```
speedy       | yarn run v0.21.3
speedy       | $ node ./src/index.js
speedy       | speedy settings: { SPEEDY_DB_HOST: 'influxdb',
speedy       |   SPEEDY_DB_NAME: 'speedy',
speedy       |   SPEEDY_DB_PORT: 8086,
speedy       |   SPEEDY_INTERVAL: '"* * * * *"',
speedy       |   SPEEDY_MAX_TIME: 5000 }
speedy       | Done in 0.23s.
```

**Comment by tstackhouse** [comment]
So I figured out what was happening, `node-schedule` was silently choking on my config.  Here is my original entry in `docker-compose.yml`:

```
  speedy:
    container_name: 'speedy'
    restart: 'unless-stopped'
    image: 'stefanwalther/speedy'
    depends_on:
      - 'influxdb'
    environment:
      - SPEEDY_DB_NAME=speedy
      - INFLUXDB_DB=speedy
      - SPEEDY_DB_HOST=influxdb
      - SPEEDY_DB_PORT=8086
      - SPEEDY_INTERVAL="* * * * *"
```

I thought I needed the quotes in the string because of the string involved, but it caused silent failures.  Making it simply `SPEEDY_INTERVAL=* * * * *` fixed the problem.  It would be nice to have some improved error handling and reporting on this container.  I may submit a PR with just that as well as some enhanced reporting, i.e. raw numbers, ping, server(s) used, etc.
